<?php
$this->headTitle('Благодаря');
?>

<div class="row">
<div class="col-md-offset-4 col-md-5">
<h1>Възстановяване на парола</h1>

<?php if ($id=='sent'): ?>
<p>
    Линк за възстояване на паролата е изпратен на вашия емейл адрес
</p>
<?php elseif ($id=='invalid-email'): ?>
<p>
    Този емейл не е регистриран
</p>
<?php elseif ($id=='set'): ?>
<p>
    Вашата нова парола беше успешно изпратена
</p>
<p>
    Обратно към <a href="<?= $this->url('login'); ?>">вход</a>.
</p>
<?php elseif ($id=='failed'): ?>

    Невелиден ключ. Моля върнете се
    <a href="<?= $this->url('reset-password') ?>">тук</a> опитайте отново.
</p>
<?php endif; ?>
</div>
</div>    