<div class="row">
    <div class="col-md-offset-4 col-md-5">
        <h3>Изиграни игри до момента: <?= $stat['all']; ?></h3>
        <h3>Спечелени игри до момента: <?= $stat['wins']; ?></h3>
        <h3>Загубени игри до момента: <?= $stat['loss']; ?></h3>
        <h3>Незавършени игри: <?= $stat['notFinished']; ?></h3>
        <h3>По букви: <?= $stat['byLetter']; ?></h3>
        <h3>По цяла дума: <?= $stat['byWord']; ?></h3>

    </div>

</div>